# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 78dbfd5611e3b72d8f09fb8684817b007c7a6edf

{
  "title": "new",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token f62eabf8ecb1fc0ff7c4cdf77d5a7a7e29e54c90

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
Authorization: Token 78dbfd5611e3b72d8f09fb8684817b007c7a6edf

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-01-24
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# удаление данных
DELETE {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token f62eabf8ecb1fc0ff7c4cdf77d5a7a7e29e54c90
